// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'batch.dart';
import 'decoder.dart';
import 'exif.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 批量处理文件（推荐）：Dart 传路径列表，Rust rayon 并行计算
Future<List<FileMeta>> processFileBatch({required List<String> paths}) =>
    RustLib.instance.api.crateApiProcessFileBatch(paths: paths);

/// 生成缩略图，返回 JPEG 字节数组
Future<ThumbnailResult?> makeThumbnail(
        {required String path,
        required int maxW,
        required int maxH,
        required int quality}) =>
    RustLib.instance.api.crateApiMakeThumbnail(
        path: path, maxW: maxW, maxH: maxH, quality: quality);

/// 单文件 MD5（兜底用，批量场景用 process_file_batch）
Future<String?> computeMd5({required String path}) =>
    RustLib.instance.api.crateApiComputeMd5(path: path);

/// 原生库版本信息
Future<String> nativeVersion() => RustLib.instance.api.crateApiNativeVersion();
