// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'exif.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 单文件处理结果（供 FFI 导出）
class FileMeta {
  final String filePath;
  final String? md5;
  final BigInt fileSize;
  final PlatformInt64 fileModifiedSecs;
  final ExifData? exif;

  const FileMeta({
    required this.filePath,
    this.md5,
    required this.fileSize,
    required this.fileModifiedSecs,
    this.exif,
  });

  @override
  int get hashCode =>
      filePath.hashCode ^
      md5.hashCode ^
      fileSize.hashCode ^
      fileModifiedSecs.hashCode ^
      exif.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileMeta &&
          runtimeType == other.runtimeType &&
          filePath == other.filePath &&
          md5 == other.md5 &&
          fileSize == other.fileSize &&
          fileModifiedSecs == other.fileModifiedSecs &&
          exif == other.exif;
}
