// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ThumbnailResult {
  final Uint8List jpegBytes;
  final int width;
  final int height;

  const ThumbnailResult({
    required this.jpegBytes,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode => jpegBytes.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThumbnailResult &&
          runtimeType == other.runtimeType &&
          jpegBytes == other.jpegBytes &&
          width == other.width &&
          height == other.height;
}
