// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// EXIF 元数据
class ExifData {
  final String? dateTaken;
  final String? make;
  final String? model;
  final String? iso;
  final String? fNumber;
  final String? exposure;
  final String? focal;
  final double? lat;
  final double? lng;
  final int? imageWidth;
  final int? imageHeight;
  final String? orientation;

  const ExifData({
    this.dateTaken,
    this.make,
    this.model,
    this.iso,
    this.fNumber,
    this.exposure,
    this.focal,
    this.lat,
    this.lng,
    this.imageWidth,
    this.imageHeight,
    this.orientation,
  });

  @override
  int get hashCode =>
      dateTaken.hashCode ^
      make.hashCode ^
      model.hashCode ^
      iso.hashCode ^
      fNumber.hashCode ^
      exposure.hashCode ^
      focal.hashCode ^
      lat.hashCode ^
      lng.hashCode ^
      imageWidth.hashCode ^
      imageHeight.hashCode ^
      orientation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExifData &&
          runtimeType == other.runtimeType &&
          dateTaken == other.dateTaken &&
          make == other.make &&
          model == other.model &&
          iso == other.iso &&
          fNumber == other.fNumber &&
          exposure == other.exposure &&
          focal == other.focal &&
          lat == other.lat &&
          lng == other.lng &&
          imageWidth == other.imageWidth &&
          imageHeight == other.imageHeight &&
          orientation == other.orientation;
}
